### ISSUE TITLE
The installation guide doesn't work as-is

### ISSUE THREAD

**Issue by wlinna** [opensourceBIM/voxelization_toolkit#11]
I wanted to try voxelization_toolkit, but after installing. The steps I tried:

1. `conda create --name voxelization`
2. `conda activate voxelization`
3. `conda install -c ifcopenshell voxelization_toolkit`
4. `~/Software/mambaforge/envs/voxelization/bin/voxec`

Result: 
`error while loading shared libraries: libboost_regex.so.1.74.0: cannot open shared object file: No such file or directory`

I figured out I could try installing `ifcopenshell` (should probably be documented).

1. `conda install -c ifcopenshell ifcopenshell`
2. `~/Software/mambaforge/envs/voxelization/bin/voxec`

Result
`voxec: symbol lookup error: /home/william/Software/mambaforge/envs/voxelization/bin/voxec: undefined symbol: _ZNK16Standard_Failure14GetStackStringEv`

Do I need to install something else? Or is this a wrong way to run it?

I'm on Pop!_OS 22.04 (similar to Ubuntu 22.04) , conda 22.9.0, Python 3.10.

**Comment by aothms** [comment]
Ok, I guess some of the dependencies are not correctly articulated, I had a hard time getting something to work without a ton of conflicts.

Installing IfcOpenShell was a good move, but the code here is compiled against the conda-forge version. Could you try

```
conda install -c conda-forge ifcopenshell
```

instead?

**Comment by wlinna** [comment]
ran
1. `conda uninstall -c ifcopenshell ifcopenshell`
2. `conda install -c conda-forge ifcopenshell`
3. `~/Software/mambaforge/envs/voxelization/bin/voxec --help`

And it works. Thanks for the quick response!

**Comment by aothms** [comment]
Cool, thanks for reporting, updated the readme https://github.com/opensourceBIM/voxelization_toolkit/blob/master/README.md#installation
