### ISSUE TITLE
Boost install from IfcOpenShell not recognized

### ISSUE THREAD

**Issue by schaubli** [opensourceBIM/voxelization_toolkit#8]
I used some changes from https://github.com/opensourceBIM/voxelization_toolkit/pull/7 (props to @johltn) to fix the Visual Studio 2019 build.
Unfortunately the boost library from `IFCOPENSHELL_ROOT` aren't found even though the `BOOST_ROOT` and `BOOST_LIBRARYDIR` both resolve to the correct folders and the files are installed in the library folder. It also recognizes the correct version is 1.74.0 but not the individual components. Error message is: `Could NOT find Boost (missing: regex iostreams system filesystem) (found version "1.74.0")`
The `BOOST_LIBRARYDIR` points to the folder containing these files:

<img width="816" alt="Screen Shot 2022-04-01 at 11 55 13" src="https://user-images.githubusercontent.com/18361732/161242363-ae60703b-bd90-46ef-9878-e6f3ad260e02.png">

Is Boost expecting these files to have a different name, or what else could be causing this? 
Please let me know if you need any other information that could help you help me with this issue. 
Thank you!

**Comment by schaubli** [comment]
Managed to solve this after setting to Boost_USE_STATIC_LIBS to ON which I had accidentally changed apparently. 
With v0.7.0 IfcOpenShell, I also had to change `IfcEntityList` to `aggregate_of_instance`

**Comment by aothms** [comment]
>  With v0.7.0 IfcOpenShell, I also had to change IfcEntityList to aggregate_of_instance

Correct, if you find the time to send in a Pull Request with some of the conditional fixes, it'd be highly appreciated.
